#!/usr/bin/env php
<?php require_once __DIR__.'/vendor/autoload.php';

// Configure Pimple Container; using the 'dependencies.yml'
//  file located in the config directory.
$container = new Pimple\Container();
(new G\Yaml2Pimple\YamlFileLoader(
        new G\Yaml2Pimple\ContainerBuilder($container),
        new Symfony\Component\Config\FileLocator(__DIR__.'/config')
    ))->load('dependencies.yml');


// Execute CronRunner tasks
(new \CronRunner\Runner( $container , in_array('--debug', $argv))
    ->executeTasks();